import { Worker } from "node:worker_threads";

/**
 * Out-of-process kill switch (ship gate #1, §8, §11).
 *
 * The failure this exists for is NOT "the operator wants to stop trading" —
 * that is just a button. It is "the trading loop is wedged and still holding
 * exposure": an infinite loop, a synchronous stall, a pathological GC pause, a
 * deadlocked await. In every one of those cases a kill switch living on the
 * main event loop is exactly as stuck as the thing it is meant to stop.
 *
 * So it runs on a dedicated worker thread with its OWN event loop and its own
 * HTTP listener, and it talks to the venue directly. It deliberately shares no
 * state with the engine — not the order map, not the position cache, nothing —
 * because any shared structure is a structure that can be mid-mutation when the
 * main thread hangs.
 *
 * It is a blunt instrument on purpose: cancel everything, close everything, ask
 * no questions. Nuance is what the risk engine is for.
 */

export interface KillSwitchOptions {
  port: number;
  host?: string;
  /** Bearer token required to trigger. Generated by the caller. */
  token: string;
  /** Bybit REST base, e.g. https://api-testnet.bybit.com */
  restBase: string;
  apiKey: string;
  apiSecret: string;
  /** Settlement coin whose positions get flattened. */
  settleCoin?: string;
  /** When true, everything runs except the actual venue calls. */
  dryRun?: boolean;
  onLog?: (message: string) => void;
}

export interface KillSwitchHandle {
  /** Stops the worker. */
  stop(): Promise<void>;
  readonly port: number;
}

/**
 * Worker source.
 *
 * Inlined rather than shipped as a separate file so the switch cannot fail to
 * start because of a path or bundling problem. A kill switch that does not come
 * up is worse than none: it is a kill switch you believe you have.
 */
const WORKER_SOURCE = `
const http = require("node:http");
const crypto = require("node:crypto");
const { workerData, parentPort } = require("node:worker_threads");

const { port, host, token, restBase, apiKey, apiSecret, settleCoin, dryRun } = workerData;

const log = (m) => parentPort?.postMessage({ type: "log", message: m });

function sign(timestamp, recvWindow, payload) {
  return crypto
    .createHmac("sha256", apiSecret)
    .update(timestamp + apiKey + recvWindow + payload)
    .digest("hex");
}

async function bybitPost(path, body) {
  if (dryRun) return { dryRun: true, method: "POST", path, body };

  const timestamp = String(Date.now());
  const recvWindow = "5000";
  const payload = JSON.stringify(body);

  const res = await fetch(restBase + path, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-BAPI-API-KEY": apiKey,
      "X-BAPI-TIMESTAMP": timestamp,
      "X-BAPI-RECV-WINDOW": recvWindow,
      "X-BAPI-SIGN": sign(timestamp, recvWindow, payload),
      "X-BAPI-SIGN-TYPE": "2",
    },
    body: payload,
    signal: AbortSignal.timeout(10000),
  });
  return await res.json();
}

async function bybitGet(path, params) {
  const query = Object.entries(params)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([k, v]) => k + "=" + v)
    .join("&");

  if (dryRun) return { dryRun: true, method: "GET", path, query, result: { list: [] } };

  const timestamp = String(Date.now());
  const recvWindow = "5000";

  const res = await fetch(restBase + path + "?" + query, {
    headers: {
      "X-BAPI-API-KEY": apiKey,
      "X-BAPI-TIMESTAMP": timestamp,
      "X-BAPI-RECV-WINDOW": recvWindow,
      // A signed GET signs the query string, not a body.
      "X-BAPI-SIGN": sign(timestamp, recvWindow, query),
      "X-BAPI-SIGN-TYPE": "2",
    },
    signal: AbortSignal.timeout(10000),
  });
  return await res.json();
}

/**
 * Cancel first, then flatten.
 *
 * Order matters: flattening while resting orders are still live can have them
 * fill against the flattening trade and re-open the position just closed.
 *
 * Bybit v5 has no single "close everything" endpoint, so flattening means
 * listing open positions and sending a reduce-only market order per symbol.
 * Each is attempted independently — a partial flatten beats none, and one
 * symbol failing must not abandon the rest.
 */
async function panic() {
  const steps = [];

  try {
    steps.push({
      step: "cancelAll",
      result: await bybitPost("/v5/order/cancel-all", { category: "linear", settleCoin }),
    });
  } catch (e) {
    steps.push({ step: "cancelAll", error: String(e) });
  }

  let positions = [];
  try {
    const listed = await bybitGet("/v5/position/list", { category: "linear", settleCoin });
    positions = (listed && listed.result && listed.result.list) || [];
    steps.push({ step: "listPositions", count: positions.length });
  } catch (e) {
    steps.push({ step: "listPositions", error: String(e) });
  }

  const closes = [];
  for (const p of positions) {
    const size = Number(p.size);
    if (!Number.isFinite(size) || size <= 0) continue;

    try {
      closes.push(await bybitPost("/v5/order/create", {
        category: "linear",
        symbol: p.symbol,
        // Opposite side of the position, reduce-only so it can only ever
        // shrink exposure — never accidentally open the other way.
        side: p.side === "Buy" ? "Sell" : "Buy",
        orderType: "Market",
        qty: String(size),
        reduceOnly: true,
      }));
    } catch (e) {
      closes.push({ symbol: p.symbol, error: String(e) });
    }
  }
  steps.push({ step: "closeAll", closed: closes.length, results: closes });

  return steps;
}

let armed = true;
let lastTrigger = null;

const server = http.createServer(async (req, res) => {
  const send = (code, body) => {
    res.writeHead(code, { "Content-Type": "application/json" });
    res.end(JSON.stringify(body));
  };

  const presented = (req.headers.authorization || "").replace(/^Bearer /, "");
  const a = Buffer.from(presented);
  const b = Buffer.from(token);
  const authorised = a.length === b.length && crypto.timingSafeEqual(a, b);

  // /health is unauthenticated so a monitor can verify the switch is alive
  // without holding the credential that can fire it.
  if (req.url === "/health") return send(200, { ok: true, armed, lastTrigger });
  if (!authorised) return send(401, { error: "unauthorised" });

  if (req.method === "POST" && req.url === "/kill") {
    lastTrigger = Date.now();
    armed = false;
    log("KILL SWITCH TRIGGERED");
    const steps = await panic();
    parentPort?.postMessage({ type: "triggered", at: lastTrigger, steps });
    return send(200, { ok: true, triggeredAt: lastTrigger, steps });
  }

  if (req.method === "POST" && req.url === "/rearm") {
    armed = true;
    return send(200, { ok: true, armed });
  }

  send(404, { error: "not found" });
});

server.listen(port, host, () => {
  log("kill switch listening on " + host + ":" + port);
  parentPort?.postMessage({ type: "ready", port });
});
`;

export async function startKillSwitch(options: KillSwitchOptions): Promise<KillSwitchHandle> {
  const worker = new Worker(WORKER_SOURCE, {
    eval: true,
    workerData: {
      port: options.port,
      host: options.host ?? "127.0.0.1",
      token: options.token,
      restBase: options.restBase,
      apiKey: options.apiKey,
      apiSecret: options.apiSecret,
      settleCoin: options.settleCoin ?? "USDT",
      dryRun: options.dryRun ?? false,
    },
  });

  // Do not hold the process open on the switch alone; it is a safety device,
  // not a reason to keep running.
  worker.unref();

  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error("Kill switch failed to start")), 10_000);
    timer.unref?.();

    worker.on("message", (message: { type: string; message?: string }) => {
      if (message.type === "log" && message.message) options.onLog?.(message.message);
      if (message.type === "ready") {
        clearTimeout(timer);
        resolve();
      }
    });
    worker.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
  });

  return {
    port: options.port,
    stop: async () => {
      await worker.terminate();
    },
  };
}
